# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:auuUla+eX8k/9ohtfNd6oNBka14VymeVUloK6hR/AytIHUE53kCp5m7K2yJONWYZaAaNjno=,iv:C/8QmxO6ht/2UI9hsCnGSEZgRI5dm1uYZOEWon1X034=,tag:LKloGQO4JRcAUKnZCSn4Xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBib0ZIQUJWai9Jdm8rdHNF
            c2xyNHl6dnQ3SFdQaFFkbk5LOXJkcGpLRldrClRMb0hTQTZwcUdFdlAxd0dXdjVo
            cCtsM0FRNlh3ejlnM05SZC9ESVZ6Y3MKLS0tIFVwUWhjdXpSeDdkY1VKTldyOFRJ
            UzR5YVpLb2huRW5icVFZTHhmaW1iVU0K9y86eu/83ba3qYKsLDEJ0ZwyYgHv2A3N
            ernTgk1JZvPsCxm8RPBgMB2W8lTKGgvVkzEMDrf73xqHtvjrf2fjWQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fa4w3h22pca5exw0z2hsa0syu4kley69l722gupsnnhhz76a6sqst2wgyl
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T01:50:34Z"
    mac: ENC[AES256_GCM,data:rCUzhFtra1MKcXAu/QCOwFzdDbHDe3H1cZyCD57trlC+Dj6DmAStvrVMaiKzOscl6v7M7CPojIB4EUoZJve1CHHoCaP8MQdY5MW7hf2FHlaqLng/+gmoHhkwcOAwv6GXW1pI+Mc4JUzpozWtRXJD/n0pK8OawraaL1p1G9mVsGM=,iv:SAGt0tfO1PK/Qj24MGeEeICTdbG1p13WjnjoZxsBKIk=,tag:pFFMVjD6lPozBBmEhXQCRg==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
