---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app calibre
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      calibre:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: v4.0.6
            env:
              TZ: "America/Toronto"
              PUID: 1000
              PGID: 1000
              HARDCOVER_TOKEN: "${SECRET_HARDCOVER_API_TOKEN}"
            probes:
              liveness: &probes
                enabled: true
              readiness: *probes
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 8083
    route:
      app:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: *app
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: 192.168.86.200
            path: "/mnt/vault/media"
        globalMounts:
          - path: /cwa-book-ingest
            subPath: books/ingest
          - path: /calibre-library
            subPath: books/library
