---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
components:
  - ../../components/common
resources:
  - ./echo/ks.yaml
  - ./iperf3/ks.yaml
  - ./ollama/ks.yaml
  - ./karakeep/ks.yaml
  - ./plex/ks.yaml
  - ./tautulli/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./radarr/ks.yaml
