---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mosquitto
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      mosquitto:
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/eclipse-mosquitto
              tag: 2.0.22
            env:
              TZ: "America/Toronto"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    configMaps:
      config:
        data:
          mosquitto.conf: |-
            allow_anonymous false
            autosave_interval 60
            connection_messages false
            listener 1883
            per_listener_settings false
            persistence true
            persistence_location /config
            password_file /mosquitto/config/mosquitto_pwd/mosquitto_pwd
    persistence:
      config:
        existingClaim: *app
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
      mosquitto-pwd:
        type: secret
        name: mosquitto-pwd
        items:
          - key: mosquitto_pwd
            path: mosquitto_pwd
        globalMounts:
          - path: /mosquitto/config/mosquitto_pwd
    service:
      app:
        type: LoadBalancer
        loadBalancerIP: 192.168.86.232
        ports:
          http:
            port: 1883
