---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app multus
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      multus:
        type: daemonset
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/k8snetworkplumbingwg/multus-cni
              tag: v4.2.2@sha256:2e8c2cfa47c537d9179ef0125cfcdab7e8f9bc0a2880fceac1d12e5f80fc9f4d
            args:
              - --multus-conf-file=auto
              - --multus-kubeconfig-file-host=/var/lib/rancher/k3s/agent/etc/cni/net.d/multus.d/multus.kubeconfig
              - --cleanup-config-on-exit=true
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 512Mi
            securityContext:
              privileged: true
        initContainers:
          init-cni-plugins:
            image:
              repository: ghcr.io/angelnu/cni-plugins
              tag: 1.6.1@sha256:a5a7976ba17b405072143c61ee55660d170eb974e0f50fb39acb365458a47a7f
            command:
              - sh
              - -c
              - set -e -x; cp -f /cni-plugins/bin/* /host/opt/cni/bin/
            securityContext:
              privileged: true
    defaultPodOptions:
      hostNetwork: true
      priorityClassName: system-node-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
    persistence:
      cni:
        type: hostPath
        hostPath: /etc/cni/net.d
        globalMounts:
          - path: /host/etc/cni/net.d
      cnibin:
        type: hostPath
        hostPath: /opt/cni/bin
        globalMounts:
          - path: /host/opt/cni/bin
      host-run-netns:
        type: hostPath
        hostPath: /run/netns
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /run/netns
            mountPropagation: HostToContainer
      host-var-lib-cni:
        type: hostPath
        hostPath: /var/lib/cni
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /var/lib/cni
      host-var-lib-kubelet:
        type: hostPath
        hostPath: /var/lib/kubelet
        hostPathType: DirectoryOrCreate
        globalMounts:
          - path: /var/lib/kubelet
    serviceAccount:
      create: true
      name: *app
