---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mc-neoforge
spec:
  interval: 5m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: minecraft-server-charts
  values:
    replicaCount: 1
    resources:
      requests:
        memory: 2Gi
      limits:
        memory: 6Gi
    minecraftServer:
      eula: "TRUE"
      type: "NEOFORGE"
      version: "1.21.1"
      gameMode: survival
      levelSeed: "neoforge"
      overrideServerProperties: true
      maxPlayers: 10
      whitelist: "phybros,gimgam5000"
      ops: "phybros"
      viewDistance: 10
      difficulty: "normal"
      icon: "https://minecraft.wiki/images/Creeper_Head_%28S%29_JE1.png"
      motd: "\u00a7b\u00a7lCreate: Aeronautics"
      memory: 5120M
      serviceType: LoadBalancer
      loadBalancerIP: 192.168.86.222
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
