apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LhrXAwNPclU=,iv:0Dx5SYelSp3j87bSlzjGqNyCGVFQ7XLsBdglMWtI5FE=,tag:JHg+E4HdFjRdHF9Ie0erXQ==,type:str]
    #ENC[AES256_GCM,data:jlU4uSrvrCZcWiosPY/gkvd0Y61Xsg==,iv:VFS7bDoKjF/aGcmVWGuIJsCg9IYUlDaw/dkJz0mlKn4=,tag:jitc8V/utnXMqnrllnQVDA==,type:comment]
    SECRET_RESTIC_REPO: ENC[AES256_GCM,data:3r2qtebC+MToYr8K7WI1KFvzZtlIIjhGTqz/5zlLXmehkWfO,iv:F3tcwyZ+aZ1jFjG884DOdtmcux4DkjEXutuqJnPks1A=,tag:QXPtC38D5VjvXUsQrwS0BA==,type:str]
    SECRET_RESTIC_PASSWORD: ENC[AES256_GCM,data:vFVic+9vls6zfeH9aU+4VaodES1oR9lr,iv:TY2CQdRQW5BGa9qxCutKvk8U9YD17NdbTFpSn4rZcMQ=,tag:SX0vvcvnPOZR3pQA5isDLQ==,type:str]
    SECRET_RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iJ6T+i9EjYV8ISNl9GVB59jeXbU=,iv:9NizUbyXIq7DvkJum2qk7BKuv0S/LvSuXvaXu+JG+f4=,tag:wVJ9ikfCcWb5NuOEW3VahA==,type:str]
    SECRET_RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jjq0AFM9SIxAoh42hZWX5zmiYlzS4vs1qHipol++OA7KjlrKMO9Zsw==,iv:RY4lguJwtLlNY9x4u60zQtstuLrQOSAjCkzjnhdwweU=,tag:/lUT7wGDD5oM7OPZhzHcuw==,type:str]
sops:
    age:
        - recipient: age1fa4w3h22pca5exw0z2hsa0syu4kley69l722gupsnnhhz76a6sqst2wgyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV1R1MU55cWprSHRsZ2xN
            Z3p2VHI3WUtBZEFMSmZPc0FUY1dhOW5TOHhFCno1MThGQkxHV2hzUU1xbmdLVXVa
            VHFtNTlRSTg3b2xmUC9tMklsZ2Z1Z2MKLS0tIFEzYVM3ZnlYb3ZibXMxVkxlUGVu
            RjlhTWNKd0pMd3hIUVlNNWtkMXovUlUK1D4vpaDzABv0uOyJEloySNEPzNhkiQBD
            JZBWerBb6cdgnwVabH05f6+DAOVMZ+mi1gPWsDlh/76Lt3WsRiq3sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-16T00:12:47Z"
    mac: ENC[AES256_GCM,data:siKrDzCu+QBPvMgd3iBSag6M/Bs2m9GoeEP+6qggafJqgPfQYHxcImEak6aXjk3OAtV0SGUhXy4KnWUjEIv4o88LYcOLFc+v3lTGU5ooo+9JA9tr+nKVTejZ+0ni4tFj8F23VZqXszmQZFkhrzD12v3FiA6Yj5HeJajcTgCtiEw=,iv:1Ujwg60DaTcjGY3XBIYsdZXFqZHtMBnHIPCsEINVeRs=,tag:fO4EfkWmZVq5s2YDWSCCYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
