apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LhrXAwNPclU=,iv:0Dx5SYelSp3j87bSlzjGqNyCGVFQ7XLsBdglMWtI5FE=,tag:JHg+E4HdFjRdHF9Ie0erXQ==,type:str]
    #ENC[AES256_GCM,data:jlU4uSrvrCZcWiosPY/gkvd0Y61Xsg==,iv:VFS7bDoKjF/aGcmVWGuIJsCg9IYUlDaw/dkJz0mlKn4=,tag:jitc8V/utnXMqnrllnQVDA==,type:comment]
    SECRET_RESTIC_REPO: ENC[AES256_GCM,data:3r2qtebC+MToYr8K7WI1KFvzZtlIIjhGTqz/5zlLXmehkWfO,iv:F3tcwyZ+aZ1jFjG884DOdtmcux4DkjEXutuqJnPks1A=,tag:QXPtC38D5VjvXUsQrwS0BA==,type:str]
    SECRET_RESTIC_PASSWORD: ENC[AES256_GCM,data:vFVic+9vls6zfeH9aU+4VaodES1oR9lr,iv:TY2CQdRQW5BGa9qxCutKvk8U9YD17NdbTFpSn4rZcMQ=,tag:SX0vvcvnPOZR3pQA5isDLQ==,type:str]
    SECRET_RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:iJ6T+i9EjYV8ISNl9GVB59jeXbU=,iv:9NizUbyXIq7DvkJum2qk7BKuv0S/LvSuXvaXu+JG+f4=,tag:wVJ9ikfCcWb5NuOEW3VahA==,type:str]
    SECRET_RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Jjq0AFM9SIxAoh42hZWX5zmiYlzS4vs1qHipol++OA7KjlrKMO9Zsw==,iv:RY4lguJwtLlNY9x4u60zQtstuLrQOSAjCkzjnhdwweU=,tag:/lUT7wGDD5oM7OPZhzHcuw==,type:str]
    SECRET_NEXTAUTH: ENC[AES256_GCM,data:M3oTuDC/AscAMhxm+oi1brXxZiGol0o31/rqRwY=,iv:ZwcHCKwOB54djDN77BOL1ZZETU8ZrUGnxuHm7cfOQUg=,tag:KxqtJYbuCamruhk/YGN3TA==,type:str]
    SECRET_MEILI: ENC[AES256_GCM,data:IsbFBPEcL3BnyESeUpUj/xzVQ8CiCp1jIyRndb0=,iv:+TuSrb8HHIinAHcjj5cA8AUEN+x+kx7si+CkJ+fjMGg=,tag:FsQxyD1ysJtXmDNXGiiy5A==,type:str]
    SECRET_DISCORD_WEBHOOK: ENC[AES256_GCM,data:AVIFo6AVpP0x4ruWV8+a5Bayv6ohoi4nyWRBc2xk6pJLrxMs0uAN3+TH8wV5c9cfQkVQppZskPk0wjdomRjlj9Z/HjFMHCl6h/H+kyKNci2vjJmRwhv7Uvx433MVkGBVFzciHftKMwdFu7mZ9h0B4zZV2YJFo8fBMA==,iv:ywQDkb5YINK1qwjrJmAXKJOexz+dKA4HBeGllrZbV7A=,tag:+56+j/H59mZLZPT6Bodd+A==,type:str]
    #ENC[AES256_GCM,data:qvhiO+kZjrfFBl6fk9y1pn8=,iv:WAmnKZqwBA25FmBerRQq6ms8bO2IZaBk+zfxSpcIDHA=,tag:6cKgfHvqqPQUXvYSl4DX1A==,type:comment]
    SECRET_APPDAEMON_TOKEN: ENC[AES256_GCM,data:GmAqxClDdNFAXMVmBhSlPuIcHhWf1174wpmvl/vTsw8vXOyv/f0PKufjhN/MFv/Lk4qTD8J/3sGqUjCJCFXMLwr8Or4HFpGhUx2kSH7xVt+KT8X1J0fT7Dlhqu6E7JQXqjZ7htaaYFcNaHo07ZcrEi/wQqaZW5TIPJeeXKcSlKRE9ueWSgp/PZ1QplVhs1ShEIODvGoi7omOww3tU5qUknd1/eQTNnUz/RhJj0GAFFeWzYBtpHff,iv:0FVA6Jx7/2YBKHytcTbah01pm3WsjqSvcLSoa4REpDU=,tag:tE8Hiy6MMvyvDyMcZJEr2w==,type:str]
    SECRET_ELEVATION: ENC[AES256_GCM,data:ow==,iv:KEapR8bCfyALm9pO5yeYOrCLb1LXwhoMaE4eKMPLlyk=,tag:RhZK2662xJ1+q/mUDPHKuQ==,type:str]
    SECRET_LAT: ENC[AES256_GCM,data:mgs//E49g6JeYsyLHUwjb4hP,iv:xFwwd4caQioUZMbCz90Fzwk5/ih+4PKsahVbcUHPufY=,tag:WLQDHJqhkqbFG/kn9RSyCg==,type:str]
    SECRET_LNG: ENC[AES256_GCM,data:96PK4uhD4PSP485k7GxXEBR8,iv:3BVR15fEzqJQXlZArVIKiQjtS8ytVA+k9laqmyNTD2E=,tag:7AFoZ//moBvawUo2EfJPKw==,type:str]
sops:
    age:
        - recipient: age1fa4w3h22pca5exw0z2hsa0syu4kley69l722gupsnnhhz76a6sqst2wgyl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV1R1MU55cWprSHRsZ2xN
            Z3p2VHI3WUtBZEFMSmZPc0FUY1dhOW5TOHhFCno1MThGQkxHV2hzUU1xbmdLVXVa
            VHFtNTlRSTg3b2xmUC9tMklsZ2Z1Z2MKLS0tIFEzYVM3ZnlYb3ZibXMxVkxlUGVu
            RjlhTWNKd0pMd3hIUVlNNWtkMXovUlUK1D4vpaDzABv0uOyJEloySNEPzNhkiQBD
            JZBWerBb6cdgnwVabH05f6+DAOVMZ+mi1gPWsDlh/76Lt3WsRiq3sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-21T18:10:26Z"
    mac: ENC[AES256_GCM,data:byWEqAKSWIm5xyUPdJU0JZub2ZVBTINpP70O3bWFWclAEV23ph3dUG/iQvmVvBOfVwSwZP38dLaA0/pM9HSYO3t6A2559WP//hGgfJrjpPy9kfHBsAYPxHJtdLouT6bN+E5HKshXPFDPXRGc7lyJVxG/d4M4YBBxH0p1whWgNJQ=,iv:SY9oc5bQckGllaU08pUQA0ucivRAw73+FCIyTrR0VWo=,tag:SAhHL2eIFRoKKbGoSvbP4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
